# Generated by Django 3.2.9 on 2022-04-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_auto_20220421_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
