# Generated by Django 3.2.9 on 2022-04-21 15:29

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0007_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(upload_to=app_users.models.path_and_rename, verbose_name='Изображение профиля*'),
        ),
    ]
