# Generated by Django 3.2.9 on 2022-05-01 15:07

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_auto_20220502_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(default='images/users/default-avatar.png', upload_to=app_users.models.upload_profile_image, verbose_name='Аватар'),
        ),
    ]
