# Generated by Django 3.2.9 on 2022-05-05 07:35

import app_users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0011_alter_userprofileinfo_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(default='images/2.jpg', upload_to=app_users.models.path_and_rename, verbose_name='Аватар'),
        ),
    ]
