# Generated by Django 3.2.9 on 2022-05-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0014_alter_userprofileinfo_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Студент')], default='student', max_length=30, verbose_name='Тип студента'),
        ),
    ]
