# Generated by Django 3.2.9 on 2022-05-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0015_alter_userprofileinfo_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bio',
            field=models.CharField(blank=True, max_length=500, verbose_name='О себе'),
        ),
    ]
