# Generated by Django 3.2.9 on 2022-05-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0016_alter_userprofileinfo_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Студент')], default='student', max_length=30, verbose_name='Тип пользователя'),
        ),
    ]
