# Generated by Django 3.2.9 on 2022-05-31 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0017_alter_userprofileinfo_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofileinfo',
            options={'verbose_name': 'Информация о пользователях', 'verbose_name_plural': 'Информация о пользователях'},
        ),
    ]
