# Generated by Django 3.1.1 on 2020-09-26 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0003_auto_20200926_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='lessons', to='educate_portal.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='subjects', to='educate_portal.standard'),
        ),
    ]
