# Generated by Django 3.2.9 on 2022-04-20 05:21

from django.db import migrations, models
import educate_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0031_homework_notes_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='vidfre',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='Notes',
            field=models.FileField(blank=True, upload_to=educate_portal.models.save_lesson_files, verbose_name='файл урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='id урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Заголовок урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='position',
            field=models.PositiveSmallIntegerField(verbose_name='Номер урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='ppt',
            field=models.FileField(blank=True, upload_to=educate_portal.models.save_lesson_files, verbose_name='презентации'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=educate_portal.models.save_lesson_files, verbose_name='видео'),
        ),
    ]
