# Generated by Django 3.2.9 on 2022-04-20 06:19

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0032_auto_20220420_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='vidfre',
        ),
        migrations.AddField(
            model_name='lesson',
            name='videos',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
    ]
