# Generated by Django 3.2.9 on 2022-04-20 06:30

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0033_auto_20220420_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='videos',
            field=embed_video.fields.EmbedVideoField(default='', verbose_name='видеоыы'),
        ),
    ]
