# Generated by Django 3.2.9 on 2022-04-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0034_alter_lesson_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
    ]
