# Generated by Django 3.2.9 on 2022-04-20 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0035_remove_lesson_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='videos',
            new_name='video',
        ),
    ]
