# Generated by Django 3.2.9 on 2022-04-20 12:56

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0036_rename_videos_lesson_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='workingdays',
            name='standard',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='', verbose_name='ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='reply_body',
            field=models.TextField(max_length=500, verbose_name='ответ на комментарий'),
        ),
        migrations.DeleteModel(
            name='SlotSubject',
        ),
        migrations.DeleteModel(
            name='TimeSlots',
        ),
        migrations.DeleteModel(
            name='WorkingDays',
        ),
    ]
