# Generated by Django 3.2.9 on 2022-04-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0037_auto_20220420_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(verbose_name='Описание заметки'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок заметки'),
        ),
    ]
