# Generated by Django 3.2.9 on 2022-04-21 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0039_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
    ]
