# Generated by Django 3.2.9 on 2022-05-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0041_auto_20220502_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description2',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
