# Generated by Django 3.2.9 on 2022-05-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0042_auto_20220522_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description2',
        ),
    ]
