# Generated by Django 3.2.9 on 2022-05-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0043_auto_20220522_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_id',
        ),
    ]
