# Generated by Django 3.2.9 on 2022-05-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0044_remove_lesson_lesson_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Описание урока'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description2',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Продолжение описания'),
        ),
    ]
