# Generated by Django 3.2.9 on 2022-05-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0045_auto_20220522_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='answer_contact',
            field=models.CharField(default='', max_length=100, verbose_name='ответ администратора'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='уникальное поле в адресной строке (eng раскладка)'),
        ),
    ]
