# Generated by Django 3.2.9 on 2022-05-27 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0046_auto_20220527_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата обращения'),
        ),
    ]
