# Generated by Django 3.2.9 on 2022-05-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0047_contact_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='console',
            field=models.URLField(default='', max_length=250, verbose_name='консоль'),
        ),
    ]
