# Generated by Django 3.2.9 on 2022-05-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0050_answer_question_quiz_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_image',
            field=models.ImageField(default='', upload_to='images/quiz_image', verbose_name='Изображение викторины'),
        ),
    ]
