# Generated by Django 3.2.9 on 2022-05-31 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educate_portal', '0051_quiz_quiz_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарии', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Задания', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Уроки', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Ответы на комментарии', 'verbose_name_plural': 'Ответы на комментарии'},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'verbose_name': 'Предмет обучения', 'verbose_name_plural': 'Предмет обучения'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Категория предмета обучения', 'verbose_name_plural': 'Категория предмета обучения'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Планировщик', 'verbose_name_plural': 'Планировщик'},
        ),
    ]
